services:
  app:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://nafra:test@db:5432/parag"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - panetwork

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    networks:
      - panetwork
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage 

  
  db:
    image: postgres:16
    networks:
      - panetwork
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nafra
      POSTGRES_PASSWORD: test
      POSTGRES_DB: parag
      DATABASE_URL: "postgresql://nafra:test@db:5432/parag"

    # add secrets for .env : .env_file
    volumes:
      - postgres_data:/var/lib/postgresql/data

configs:
  qdrant_config:
    content: |
      log_level: INFO 

volumes:
  postgres_data:

networks:
  panetwork:
    driver: bridge
