services:
  app:
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://nafra:test@db:5432/parag"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - panetwork

  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

  db:
    image: postgres:16
    networks:
      - panetwork
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nafra
      POSTGRES_PASSWORD: test
      POSTGRES_DB: parag
    # add secrets for .env : .env_file
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  panetwork:
    driver: bridge
